---
####################################################
#          ModuleBuilder Configuration             #
####################################################


Encoding: UTF8
VersionedOutputDirectory: true
BuiltModuleSubdirectory: module

####################################################
#              PESTER Configuration                #
####################################################

Pester:
  Configuration:
    Run:
      Path:
        - tests/QA
        - tests/Integration
    Output:
      Verbosity: Detailed
      StackTraceVerbosity: Full
      CIFormat: Auto
    CodeCoverage:
      CoveragePercentTarget: 10 # Set to 0 to bypass
      # Set to specific filename to override the default filename.
      #OutputPath: JaCoCo_coverage.xml
      OutputEncoding: ascii
      UseBreakpoints: false
    TestResult:
      OutputFormat: NUnitXML
      OutputEncoding: ascii
  # Will look at every *.ps1 & *.psm1 under ModulePath, excepts when $_.FullName -match (Join-Path $ProjectPath $ExcludeFromCodeCoverageItem)
  ExcludeFromCodeCoverage:
    #- Templates

####################################################
#           Code Coverage Configuration            #
####################################################

CodeCoverage:
  # Filename of the file that will be outputted by the task Merge_CodeCoverage_Files.
  CodeCoverageMergedOutputFile: JaCoCo_coverage.xml
  # File pattern used to search for files under the ./output/testResults folder
  # by task Merge_CodeCoverage_Files.
  CodeCoverageFilePattern: Codecov*.xml

####################################################
#             HQRM Test Configuration              #
####################################################

DscTest:
  Pester:
    Configuration:
      Filter:
        ExcludeTag:
          - "Common Tests - New Error-Level Script Analyzer Rules"
          - "Common Tests - Validate Localization"
          - "Common Tests - Validate Example Files To Be Published"
          - "Common Tests - Validate Example Files"
      Output:
        Verbosity: Detailed
        CIFormat: Auto
      TestResult:
        OutputFormat: NUnitXML
        OutputEncoding: ascii
        OutputPath: ./output/testResults/NUnitXml_HQRM_Tests.xml
  Script:
    ExcludeSourceFile:
      - output
      - Modules/DscResource.Common
    ExcludeModuleFile:
      - Templates
      - Modules/DscResource.Common
    MainGitBranch: main

####################################################
#       Sampler Pipeline Configuration             #
####################################################
BuildWorkflow:
  '.': # "." is the default Invoke-Build workflow. It is called when no -Tasks is specified to the build.ps1
    - build
    - test

  build:
    - TestPowerShell7
    - Clean
    - Build_Module_ModuleBuilder
    - Build_NestedModules_ModuleBuilder
    - Create_Changelog_Release_Output

  pack:
    - build
    - package_module_nupkg

  hqrmtest:
    - Invoke_HQRM_Tests_Stop_On_Fail

  test:
    - TestPowerShell7
    - Pester_Tests_Stop_On_Fail
    - Pester_If_Code_Coverage_Under_Threshold
    #- hqrmtest

  publish:
    - publish_module_to_gallery
    - Publish_release_to_GitHub
    - Create_ChangeLog_GitHub_PR

ModuleBuildTasks:
  Sampler:
    - '*.build.Sampler.ib.tasks'
  Sampler.GitHubTasks:
    - '*.ib.tasks'
  DscResource.DocGenerator:
    - 'Task.*'
  DscResource.Test:
    - 'Task.*'

TaskHeader: |
  param($Path)
  ""
  "=" * 79
  Write-Build Cyan "`t`t`t$($Task.Name.replace("_"," ").ToUpper())"
  Write-Build DarkGray  "$(Get-BuildSynopsis $Task)"
  "-" * 79
  Write-Build DarkGray "  $Path"
  Write-Build DarkGray "  $($Task.InvocationInfo.ScriptName):$($Task.InvocationInfo.ScriptLineNumber)"
  ""

GitHubConfig:
  GitHubFilesToAdd:
    - 'CHANGELOG.md'
  GitHubConfigUserName: gaelcolas
  GitHubConfigUserEmail: gaelcolas@synedgy.com
  UpdateChangelogOnPrerelease: false

####################################################
#             DscResource.DocGenerator             #
####################################################
DscResource.DocGenerator:
  Generate_Conceptual_Help:
    BuiltModuleSubdirectory: Module
